#!/usr/bin/env python3
"""Sync or verify protocol examples generated by full-spectrum-engine."""
import argparse
import filecmp
import os
import shutil
import subprocess
import sys
import tempfile


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--engine-root", required=True)
    parser.add_argument("--protocol-root", default=os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    engine_root = os.path.abspath(args.engine_root)
    protocol_root = os.path.abspath(args.protocol_root)
    target = os.path.join(protocol_root, "examples", "cases", "ecommerce_chain")
    raw = os.path.join(engine_root, "examples", "governance_chain", "raw-input.ecommerce.json")
    with tempfile.TemporaryDirectory() as generated:
        subprocess.run([sys.executable, "-m", "src.governance_chain", "generate", "--input", raw, "--out", generated], cwd=engine_root, check=True)
        names = [name for name in os.listdir(generated) if name.endswith((".json", ".md"))] + ["raw-input.ecommerce.json"]
        mismatch = []
        for name in names:
            source = raw if name == "raw-input.ecommerce.json" else os.path.join(generated, name)
            destination = os.path.join(target, name)
            if args.check:
                if not os.path.exists(destination) or not filecmp.cmp(source, destination, shallow=False):
                    mismatch.append(name)
            else:
                os.makedirs(target, exist_ok=True)
                shutil.copyfile(source, destination)
        if mismatch:
            print("Engine-generated ecommerce example is out of sync: " + ", ".join(mismatch), file=sys.stderr)
            return 1
    print("Engine-generated ecommerce example is synchronized.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
